"""Golden-fixture parity tests for the indicator layer.

Plan §8.2: no indicator ships without a frozen numerical fixture, and the test
asserts **warmup NaN counts** as well as values — warmup is where independent
implementations usually diverge.

Fixtures are produced by `tools/pinets_oracle/generate_fixtures.mjs` (dev-only,
AGPL, never shipped). Regenerate them only deliberately: a fixture change is a
semantics change and must be reviewed as one.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from engine.indicators import atr, ema, rma, rsi, sma

FIXTURES = Path(__file__).parent / "fixtures"

# PineTS serializes at ~10 decimals, so 1e-9 is the tightest honest bound
# against this oracle. Our own implementations agree far more closely.
ABS_TOL = 1e-9


CSV = FIXTURES / "wilder_reference.csv"
MANIFEST = FIXTURES / "MANIFEST.json"


def _load():
    """Read the fixture CSV without pandas — keeps this test dependency-light.

    Empty cells are `na` in the oracle's output and load as NaN.
    """
    rows = CSV.read_text().strip().split("\n")
    header = rows[0].split(",")
    cols: dict[str, list[float]] = {name: [] for name in header}
    for row in rows[1:]:
        for name, cell in zip(header, row.split(",")):
            cols[name].append(np.nan if cell == "" else float(cell))

    arrays = {k: np.array(v, dtype=np.float64) for k, v in cols.items()}
    manifest = json.loads(MANIFEST.read_text())
    ohlc = {k: arrays[k] for k in ("open", "high", "low", "close")}
    series = {k: arrays[k] for k in manifest["series"]}
    return ohlc, series, manifest


@pytest.fixture(scope="module")
def fixture():
    if not CSV.exists():
        pytest.skip("fixtures missing — run tools/pinets_oracle/generate_fixtures.mjs")
    return _load()


def _compare(name, mine, expected):
    assert mine.shape == expected.shape, f"{name}: shape mismatch"

    # Warmup parity: the NaN prefix must match exactly, not approximately.
    mine_nan, exp_nan = np.isnan(mine), np.isnan(expected)
    assert mine_nan.sum() == exp_nan.sum(), (
        f"{name}: NaN count {mine_nan.sum()} != oracle {exp_nan.sum()} "
        "(warmup semantics diverge)"
    )
    assert np.array_equal(mine_nan, exp_nan), f"{name}: NaN positions differ"

    finite = ~exp_nan
    diff = np.abs(mine[finite] - expected[finite])
    assert diff.max() < ABS_TOL, (
        f"{name}: max abs diff {diff.max():.3e} exceeds {ABS_TOL:.0e} "
        f"at bar {int(np.argmax(diff))}"
    )


def test_sma20(fixture):
    ohlc, ref, _ = fixture
    _compare("sma20", sma(ohlc["close"], 20), ref["sma20"])


def test_ema20(fixture):
    ohlc, ref, _ = fixture
    _compare("ema20", ema(ohlc["close"], 20), ref["ema20"])


def test_rma20(fixture):
    ohlc, ref, _ = fixture
    _compare("rma20", rma(ohlc["close"], 20), ref["rma20"])


def test_rsi14(fixture):
    ohlc, ref, _ = fixture
    _compare("rsi14", rsi(ohlc["close"], 14), ref["rsi14"])


def test_atr14(fixture):
    ohlc, ref, _ = fixture
    _compare("atr14", atr(ohlc["high"], ohlc["low"], ohlc["close"], 14), ref["atr14"])


def test_oracle_is_pinned(fixture):
    """A fixture regenerated against a different oracle version is a new baseline."""
    _, _, manifest = fixture
    assert manifest["oracle"] == "pinets@0.9.33", (
        f"fixtures were generated by {manifest['oracle']!r}; "
        "review the diff before accepting a new oracle version"
    )
